# Generated by Django 5.1.5 on 2025-01-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_calendarevent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googlecredentials',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='googlecredentials',
            name='token_expiry',
        ),
        migrations.RemoveField(
            model_name='googlecredentials',
            name='user',
        ),
        migrations.AddField(
            model_name='googlecredentials',
            name='user_email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
    ]
